### ISSUE TITLE
Package `org-plus-contrib-8.2' is unavailable

### ISSUE THREAD

**Issue by vxe** [chrisbarrett/org-drill-table#1]
Look like there's a dependency on org-plus-contrib that isn't satisfied

org-plus-contrib is an orphan package.

```
 Status: Orphan.
Archive: n/a
Summary:
```

**Comment by milkypostman** [comment]
see milkypostman/melpa#2824

an easy solution is to change the dependency to be something installable by melpa without the need for an additional package archive.

**Comment by chrisbarrett** [comment]
Not sure what to do about this one. Emacs doesn't ship with org's contrib files, and there is no package containing `org-drill` on MELPA which I can see. This forces this package to depend on ELPA.
