### ISSUE TITLE
Show specific card titles instead of a generic one

### ISSUE THREAD

**Issue by kshenoy** [chrisbarrett/org-drill-table#5]
It uses the contents of the first column as the name of the card. For example

    * Vocab
    |-----------+---------|
    | English   | Spanish |
    |-----------+---------|
    | Today     | Hoy     |
    |-----------+---------|

if we run 'org-drill-table-generate` and, when prompted for the `DRILL_HEADING`, press enter without typing anything, it will generate the following card:

    ** Cards
    *** Today                                                            :drill:
    :PROPERTIES:
    :DRILL_CARD_TYPE: twosided
    :END:
    Translate the following word.
    **** English
    Today
    **** Spanish
    Hoy

I have the code in a branch. Let me know if you want me to submit a pull request.

This isn't a simple bugfix so I thought I'd ask first.

**Comment by chrisbarrett** [comment]
Sounds cool, send a PR 👍
