### ISSUE TITLE
Skipping cards while drilling

### ISSUE THREAD

**Issue by Tobias-Loeffler** [chrisbarrett/org-drill-table#9]
Hey,
First of all, thanks for the great extension!
While drilling, org-drill offers me the option to skip a question using the s-key. Unfortunately nothing happens when i hit s.
Greetings, Tobias

**Comment by chrisbarrett** [comment]
Hi there.

This doesn't sound like an issue with org-drill-table, but with org-drill itself, which is part of org-mode. org-drill-table just automates creating the headings for you.
